// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4491.Lifter.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4491.Lifter.Robot;

/**
 *
 */
public class  cmd_liftGotoFloor extends Command {

    public cmd_liftGotoFloor() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lift);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	System.out.println("cmd_liftGotoFloor::initialize");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//System.out.println("cmd_liftGotoFloor::execute");
    	if (!Robot.lift.isLiftAtFloor())
    	{
    		Robot.lift.moveLiftToFloor();
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	System.out.println("cmd_liftGotoFloor::isFinished");
        return Robot.lift.isLiftAtFloor();
    }

    // Called once after isFinished returns true
    protected void end() {
    	System.out.println("cmd_liftGotoFloor::end");
    	Robot.lift.stopLift();
    	Robot.lift.enableSystem();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	System.out.println("cmd_liftGotoFloor::interrupted");
    	Robot.lift.stopLift();
    }
}
