// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4491.Lifter.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc4491.Lifter.Robot;
import org.usfirst.frc4491.Lifter.RobotMap;

/**
 *
 */
public class  cmd_liftUp extends Command {
	
	int LevelGoal;
	
    public cmd_liftUp() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lift);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	LevelGoal = (int) Math.floor(Robot.lift.getLevel()) + 1;
    	System.out.println("Level goal = " + LevelGoal);
    }
    

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {

    	System.out.println("execute::max height ? = " + Robot.lift.IsMaxHeight());
    	System.out.println("execute::level = " + Robot.lift.getLevel());
    	if (!Robot.lift.IsMaxHeight() &&
    		Robot.lift.getLevel() < LevelGoal)
    	{
    		Robot.lift.SetMotorSpeed(1);    	
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	System.out.println("isFinished::max height ? = " + Robot.lift.IsMaxHeight());
    	System.out.println("isFinished::level = " + Robot.lift.getLevel());
        return Robot.lift.IsMaxHeight() ||
        	   Robot.lift.getLevel() >= LevelGoal;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.lift.SetMotorSpeed(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.lift.SetMotorSpeed(0);
    }
}
